audio_mapper_path: ./pretrained_weights/audio_mapper-50000.pth
audio_model_path: ./pretrained_weights/audio_processor/tiny.pt
audio_path: D:\PythonProjects\DigitalHuman\echomimic_v2\temp_uploads\custom_audio_1755023571.wav
auido_guider_path: ./pretrained_weights/wav2vec2-base-960h
auto_flow_path: ./pretrained_weights/AutoFlow
denoising_unet_path: ./pretrained_weights/denoising_unet.pth
inference_config: ./configs/inference/inference_v2.yaml
motion_module_path: ./pretrained_weights/motion_module.pth
output_dir: D:\PythonProjects\DigitalHuman\echomimic_v2\outputs
pose_dir: D:\PythonProjects\DigitalHuman\echomimic_v2\assets\halfbody_demo\pose\01
pose_encoder_path: ./pretrained_weights/pose_encoder.pth
pretrained_base_model_path: ./pretrained_weights/sd-image-variations-diffusers
pretrained_vae_path: ./pretrained_weights/sd-vae-ft-mse
reference_image: D:\PythonProjects\DigitalHuman\echomimic_v2\temp_uploads\custom_image_1755023571.png
reference_unet_path: ./pretrained_weights/reference_unet.pth
weight_dtype: fp16
